#!/bin/bash

# Add pre-commit hook with:
# ln -s ../../scripts/pre-commit .git/hooks/pre-commit

files_without_header=()

# Retrieve the list of newly added files
source_files=$(find karoo-sdk/src sample/src -name '*.kt' -o -name '*.java')
if [ -n "$source_files" ]
then
    # Check for Copyright statement
    for source_file in $source_files; do
        files_without_header+=($(grep -L "Copyright 2021 Hammerhead Navigation, Inc. All Rights Reserved." $source_file))
    done

    if [ -n "$files_without_header" ]
    then
        echo "Copyright license header not found in the following files:"
        for file in "${files_without_header[@]}"
        do
            :
            echo "   - $file";
        done
        exit 1;
    else
        echo "All new files have updated license header.";
        exit 0;
    fi
fi